<h1 class="title">Targeting performance of monthly cash payments at multidimensional poverty in Russia in 2000 - 2011</h1>
<h2 class="author">Markus Kainu</h2>

# Content

This article draft was prepared for 1st RLMS-HSE conference at Higher School of Economics in Moscow in May 18, 2013. Abstract describes the study as follows:

>*This paper analyses the targeting performance of monetised in-kind benefits at  household deprived in terms of income, consumption and material well-being. Monetization of in-kind benefits has been one of the major reforms in attempt to modernize Russian welfare system where vast system of in-kind benefits were monetized into monthly cash payments (MCP) following the implementation of federal law FZ-122 in 2005. This paper uses multidimensional notion of poverty as an indicator of household well-being instead of plain income commonly used in this type of analysis. Main question is to what extend monetisation reform has improved the capacity of Russian welfare state to fulfil its modern tasks of redistribution of income and reduction of poverty. Paper utilises a cross-sectional setting with over-time comparison from 2000 to 2011 using the Russian Longitudinal Monitoring Study dataset. Preliminary results confirm the earlier findings and indicate that poverty reduction and redistributive impact of MCP is low. There is no clear difference neither in coverage nor in targeting of MCP between non-poor and poor households. Situation has not improved over time.*

## Required measures



## Abstract
| Event | html | pdf | Rmd |
| --- | --- | --- | --- |
| For Moscow 2013 | [html](abstract/abstract.html) | [pdf](abstract/abstract.pdf) | [Rmd](abstract/abstract.Rmd)

## Analysis

### Desctiptive analysis

| html | Rmarkdown source |
| ---- | ---------------- |
| [Income poverty comparisons](desc_income_compare.html) | [source](desc_income_compare.Rmd) |
| [Consumption poverty comparisons](desc_consumption_compare.html)  | [source](desc_consumption_compare.Rmd) |
| [Material poverty comparisons](desc_material_compare.html)  | [source](desc_material_compare.Rmd) |
| [Descriptive figure for Moscow April 2013 presentation ](figures_moscow.html)  | [source](figures_moscow.Rmd) |

## Slides

| html | Rmarkdown source |
| ---- | ---------------- |
| [current slides](slides.html) | [source](slides.Rpres)


## Article

| pdf | Rmarkdown-source |
| --- | ---------------- |
| [Article in pdf](article.pdf) | [source](article.Rmd)
